<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BinaryTreeProj\MyBinaryTreeProj.csproj" />
    <ProjectReference Include="..\ConsoleApp1\MyLinkedListProj.csproj" />
    <ProjectReference Include="..\MyHashTable\MyHashTable.csproj" />
    <ProjectReference Include="..\MyQueue\MyQueueProj.csproj" />
    <ProjectReference Include="..\MyStackk\MyStackProj.csproj" />
  </ItemGroup>

</Project>
